mlb: cliu45_team.o cliu45_player.o cliu45_agency.o
	g++ -o mlb cliu45_team.o cliu45_player.o cliu45_agency.o

cliu45_team.o: cliu45_team.cc
	g++ -c cliu45_team.cc

cliu45_player.o: cliu45_player.cc
	g++ -c cliu45_player.cc

cliu45_agency.o: cliu45_agency.cc
	g++ -c cliu45_agency.cc
